<?php
/**
 * Implementation of hook_init().
 */
/*
function dsc_player_init() {
}
*/

/**
 * Utility function - Loads Sound Cloud player JS.
 */
function dsc_player_load_player() {
  // Set common paths.
  $module_path = drupal_get_path('module', 'dsc_player');
  
  // Default styling;
  drupal_add_css($module_path . "/theme/dsc-player-style.css");
  
  // Loading the scplayer plugin.
  drupal_add_js($module_path . "/scripts/" . "scplayer.js", 'module');
  // Finally load our initilization code.
  drupal_add_js($module_path . "/scripts/" . "scplayer_init.js");
}

/**
 * Ajax Menu callback functions.
 */
/*
function dsc_player_track_toggle_visible($tid) {
  
  $track = SoundCloudTrack::getTrack($tid);
  $track->toggleVisibility();
  
  $data = array(
    'tid' => $track->tid,
    'visible' => $track->visible,
    'callback' => 'toggleVis',
  );
  
  drupal_json($data);
}
*/